[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[rpc_endpoints]
testnet = "${TESTNET_RPC_URL}"

[etherscan]
testnet = { key = "${EXPLORER_API_KEY}", url = "${EXPLORER_API_URL}" }
